// Branded spinner for Claude Code, generated by the brand-mod skill (cofoundy/brand-skills).
// While Claude works: a turning 2×2 square of cubes + the word for the turn's phase, with one
// brand-color glint crossing both; at the end of the turn, «<word> for 12s». In the desktop app,
// the SVG logo with a soft sweep. /<brand>-spinner on|off turns it off, remembered across sessions.
import type { Register } from 'claude-code'

import { BRAND, DESKTOP_WORD, LOGO_PNG, LOGO_SVG } from './brand'
import type { Cell } from './spinner'
import { doneWord, elapsed, FRAME_MS, glintPos, hasGraphics, shimmerAt, spinnerWord, square } from './spinner'

const MUTED = '#8A97A3'

let on = true
let graphics = false
let startedAt = 0
let seed = 0
let timer: { cancel: () => void } | undefined

const stop = () => {
  timer?.cancel()
  timer = undefined
}

function cells(Text: any, list: Cell[], prefix: string) {
  return list.map((c, i) => (
    <Text key={`${prefix}${i}`} color={c.color} backgroundColor={c.bg}>{c.ch}</Text>
  ))
}

export const register: Register = hook => {
  hook('session.start', async ($, e, next) => {
    const started = await next(e)
    try {
      on = (await $.store.get('spinner')) !== 'off'
      graphics = hasGraphics({
        TMUX: await $.env.get('TMUX'),
        STY: await $.env.get('STY'),
        HERDR_ENV: await $.env.get('HERDR_ENV'),
        ZELLIJ: await $.env.get('ZELLIJ'),
        TERM_PROGRAM: await $.env.get('TERM_PROGRAM'),
        KITTY_WINDOW_ID: await $.env.get('KITTY_WINDOW_ID'),
      })
      if (e.isInteractive) await $.command.register({ name: BRAND.command, description: `${BRAND.name} spinner: on | off` })
    } catch {
      // no store or no commands: the spinner stays on
    }
    return started
  })

  hook('prompt.submit', async ($, e, next) => {
    if (on) {
      try {
        startedAt = await $.clock.now()
        seed = Math.floor(Math.random() * 1000)
        stop()
        timer = $.clock.every(FRAME_MS, () => $.ui.invalidate('ui.render'))
      } catch {
        stop()
      }
    }
    return next(e)
  })

  hook('turn.complete', async ($, e, next) => {
    stop()
    return next(e)
  })

  hook('session.end', async ($, e, next) => {
    stop()
    return next(e)
  })

  hook('command.run', { command: BRAND.command }, async ($, e) => {
    const arg = e.args.trim().toLowerCase()
    on = arg === 'on' ? true : arg === 'off' ? false : !on
    await $.store.set('spinner', on ? 'on' : 'off').catch(() => undefined)
    if (!on) stop()
    return { text: on ? `${BRAND.name} spinner on: you will see it from your next turn.` : `${BRAND.name} spinner off: back to Claude Code's own.` }
  })

  hook('ui.render', { component: 'Spinner' }, async ($, e, next) => {
    if (!on || (e.surface !== 'terminal' && e.surface !== 'desktop')) return next(e)
    const now = await $.clock.now()
    const frame = Math.floor(now / FRAME_MS)
    const word = e.props.message ?? spinnerWord(e.props.mode, seed)
    const tail = `… ${startedAt ? elapsed(now - startedAt) : ''}`
    const { Box, Image, Svg, Text } = $.ui.resolve(e) as any

    // Desktop app: the SVG logo as an image (an interactive frame is rebuilt every frame and
    // flickers) and the word in one color (the light glint tones are unreadable on a light theme).
    if (e.surface === 'desktop') {
      return (
        <Box>
          {LOGO_SVG ? <Svg key="logo" source={LOGO_SVG} alt={BRAND.name} width={16} height={16} /> : null}
          <Text> </Text>
          <Text color={DESKTOP_WORD} bold>{word}</Text>
          <Text color={MUTED}>{tail}</Text>
        </Box>
      )
    }

    const pos = glintPos([...word].length, frame)
    const logo = graphics && LOGO_PNG
    return (
      <Box>
        {cells(Text, square(now, pos), 'i')}
        <Text> </Text>
        {cells(Text, shimmerAt(word, pos - 3), 'w')}
        <Text color={MUTED}>{tail}</Text>
        {logo ? <Box flexGrow={1} /> : null}
        {logo ? <Image key="logo" source={{ png: LOGO_PNG }} columns={2} rows={1} alt=" " /> : null}
      </Box>
    )
  })

  hook('ui.render', { component: 'TurnDuration' }, ($, e, next) => {
    if (!on) return next(e)
    return next({ ...e, props: { ...e.props, word: doneWord(e.props.durationMs) } })
  })
}
