// GENERATED by skills/brand-mod/scripts/brand-mod.py from mod.json: do not edit by hand.
// In the template it holds sample values so the tests run.
export const BRAND = { name: 'Example', slug: 'example', url: 'example.com', command: 'example-spinner' }

// Brand scale, shadow to light: [0..2] darks, [3] primary, [4..6] lights, [7] white.
export const STOPS = ['#062033', '#0A3554', '#145A86', '#2185C7', '#4DA0D5', '#90C2E3', '#D3E7F4', '#FFFFFF']

// Word color in the desktop app: one color, readable on light and dark themes.
export const DESKTOP_WORD = '#2185C7'

// One word per turn phase (Spinner.props.mode).
export const WORDS: Record<string, string[]> = {
  thinking: ['Thinking'],
  'tool-use': ['Working'],
  'tool-input': ['Preparing'],
  responding: ['Answering'],
  requesting: ['Loading'],
}

// End of turn: the engine draws «<word> for 12s».
export const DONE = ['Done']

// Logo for the desktop app (SVG with an SMIL sweep) and for the terminal (64 px PNG, base64, light
// version for dark backgrounds). Empty: no logo is drawn.
export const LOGO_SVG = ''
export const LOGO_PNG = ''
